---
title: "HW09"
author: "Kelsea Emmons"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
library(tidyverse)
library(ggthemes)
```

###Part 1: DNA Strings

####Import Data
```{r}
beta_gliadin_raw <- read_lines("C:\\BI485\\emmons_kelsea\\hw09\\beta_gliadin.txt", skip = 1)
beta_gliadin_raw
```

####From Many Strings to One
```{r}
beta_gliadin <- beta_gliadin_raw %>% 
  str_replace_all("\\s", "\\") %>% 
  str_replace_all("\\d", "\\") 
beta_gliadin
```

```{r}
beta_gliadin <- beta_gliadin %>% 
  str_c(collapse = "")
beta_gliadin
```

```{r}
beta_gliadin <- beta_gliadin %>% 
  str_to_upper()
beta_gliadin
str_length(beta_gliadin)
```

####Sequence Analysis: Find the Promoter Region
```{r}
str_count(beta_gliadin, "^ACGT")
```
```{r}
str_count(beta_gliadin, "ATG")
str_count(beta_gliadin, "TGA|TAA")
```

```{r}
caat_box <- "CCAAT"
tata_box <- "CTATAA"
str_count(beta_gliadin, caat_box)
str_count(beta_gliadin, tata_box)
caat_box
tata_box
```

```{r}
caat_seq <- "CCAAT.{100,150}ATG"
str_count(beta_gliadin, caat_seq)
caat_seq
```

```{r}
tata_seq <- "CTATAA.{50,100}ATG"
str_count(beta_gliadin, tata_seq)
tata_seq
```

```{r}
caat_seqs_all <- str_extract_all(beta_gliadin, caat_seq, simplify = TRUE)
str_length(caat_seqs_all)
caat_seqs_all
```

```{r}
str_which(caat_seqs_all, tata_box)
promoter <- str_subset(caat_seqs_all, tata_box)
```

```{r}
promoter
```
```{r}
str_length(promoter)
```


###Part 2: Ants

####Import Data
```{r}
ants_raw <- read.csv("C:\\BI485\\emmons_kelsea\\hw09\\ants.csv")
ants_raw
```

####Wrangle the Data
```{r}
ants <- ants_raw %>% 
  gather(key = species, value = abundance, matches("\\w\\.\\w", ignore.case = FALSE))
ants
```
```{r}
ants <- ants %>% 
  select(-c(season))
ants
```

```{r}
ants2 <- ants %>% 
  mutate(species = str_replace(species, pattern = "(^[A-Z]*\\w{3})\\w{3,}\\.(\\w{4})\\w{2,}", replacement = "\\1\\2"))
ants2
```

```{r}
ants3 <- ants2 %>% 
  mutate(year = factor(year, levels = c("2010", "2011"), labels = c("2010", "2011"), ordered = TRUE))
ants3
```

```{r}
ants3 <- ants3 %>% 
  group_by(year, species) %>% 
  summarize(total = sum(abundance, na.rm = TRUE))
ants3
```


####Plot the Data
```{r}
ggplot(data = ants3, aes(x = reorder(species, total), y = total, group = species)) + 
  geom_line() +
  geom_point(aes(shape = year), size = 2) +
  coord_flip() +
  labs(x = NULL, y = "Total Abundance", shape = "Year") +
  theme_minimal()
```

###Part 3: Phlox Flowers

####Import and Wrangle First Data Set
```{r}
flower_size_raw <- read.csv("C:\\BI485\\emmons_kelsea\\hw09\\flower_size.csv")
flower_size_raw
```

```{r}
flower_size <- flower_size_raw %>% 
  filter(!is.na(Flower.number))
flower_size
```

```{r}
flower_size <- flower_size %>% 
  select(species = Species, cor_length = Corolla.length..cm., throat_width = Corolla.width.throat..cm.) %>% 
flower_size 
```

```{r}
flower_size <- flower_size %>% 
  separate(species, into = c("genus", "species"))
 flower_size 
```

```{r}
flower_size <- flower_size %>% 
  group_by(genus, species) %>% 
flower_size
```

```{r}
flower_size_summary <- flower_size %>% 
  summarize(mean_length = mean(cor_length), mean_width = mean(throat_width), max_length = max(cor_length), max_width = max(throat_width))
flower_size_summary
```

####Import and Wrangle the Second Data Set
```{r}
pollinators_raw <- read.csv("C:\\BI485\\emmons_kelsea\\hw09\\flower_pollinators.csv", na.strings = c("", "NA"))
pollinators_raw
```

```{r}
pollinators <- pollinators_raw %>% 
  select(-c(Color, starts_with("Source"))) %>% 
  filter(!is.na(Pollinator)) %>%
  separate(ï..Species, into = c("genus", "species")) 
pollinators
```

```{r}
pollinators <- pollinators %>% 
    separate(Pollinator, into = "Syndrome", sep = " |, ")
pollinators
```
 


####Join the Datasets
```{r}
phlox <- inner_join(flower_size_summary, pollinators, by = c("genus", "species"))
phlox
```

####Plotting
```{r}
ggplot(data = phlox) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = Syndrome))
```

```{r}
phlox2 <- phlox %>% 
  mutate(
    Syndrome = str_replace(Syndrome, "bee$", "bees"),
    Syndrome = str_replace(Syndrome, "beetle$", "beetles"))
phlox2
```

```{r}
ggplot(data = phlox2) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = Syndrome))
```

```{r}
phlox2 %>% 
  group_by(Syndrome) %>% 
  count(Syndrome)
```

```{r}
phlox3 <- phlox2 %>% 
  mutate(
    Syndrome = str_replace(Syndrome, "beetles|flies", "other insects"))
phlox3
```
```{r}
ggplot(data = phlox3) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = Syndrome))
```

```{r}
phlox4 <- phlox3 %>% 
  mutate(syndrome_group = case_when(Syndrome == "hummingbird" ~ "Bird",Syndrome == "bat" ~ "Mammal",Syndrome == "autogamous" ~ "Autogamous",TRUE ~ "Insect"))
phlox4
```

```{r}
ggplot(data = phlox4) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = syndrome_group))
```


####Improving the Plots
```{r}
ggplot(data = phlox4) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = syndrome_group)) +
  scale_color_brewer(type = "qual", palette = "Dark2")
```

```{r}
ggplot(data = phlox4) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = syndrome_group)) +
  scale_color_viridis_d(option="plasma")

```


```{r}
ggplot(data = phlox4) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = syndrome_group, shape = syndrome_group)) +
  scale_shape_manual(values = c(22:25)) +
  scale_color_viridis_d(option="plasma")
```

```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = mean_length,
                 y = mean_width,
                 shape = syndrome_group,
                 fill = syndrome_group)) +
  scale_shape_manual(values = c(22:25)) +
  scale_fill_manual(values = semo_palette)
```

```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = mean_length,
                 y = mean_width,
                 shape = syndrome_group,
                 fill = syndrome_group),
             size = 2) +
  labs(shape = "Syndrome",
       fill = "Syndrome",
       x = "Mean Length (cm)",
       y = "Mean Width (cm)") +
  theme_tufte() +
  scale_shape_manual(values = c(22:25)) +
  scale_fill_brewer(palette = "Dark2") +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12))
```

###Part 4: Customize Your Plots

####Plot 1
```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = max_length,
                 y = max_width,
                 shape = syndrome_group,
                 fill = syndrome_group),
             size = 2) +
  labs(shape = "Syndrome",
       fill = "Syndrome",
       x = "Max Length (cm)",
       y = "Max Width (cm)") +
  theme_bw() +
  scale_shape_manual(values = c(21:24)) +
  scale_fill_brewer(palette = "Set1") +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12))
```
####Plot 2
```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = max_length,
                 y = max_width, color = syndrome_group)) +
  labs(color = "Syndrome", x = "Max Length (cm)",
       y = "Max Width (cm)") +
  theme_bw() +
  scale_shape_manual(values = c(21:24)) +
  scale_color_viridis_d(option="viridis")
```

####Plot 3
```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = max_length,
                 y = max_width,
                 fill = syndrome_group, color = syndrome_group),
             size = 2) +
  labs(fill = "Syndrome", color = "Syndrome",
       x = "Max Length (cm)",
       y = "Max Width (cm)") +
  theme_minimal() +
  scale_color_viridis_d(option="magma") +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12))
```

####Plot 4 (ugly)

```{r}
ugly_colors <- c("#D2691E", "#B3C005", "#91A92A", "#7A3005")


phlox4 %>% 
  ggplot() +
  geom_point(aes(x = max_length,
                 y = max_width,
                 shape = syndrome_group,
                 fill = syndrome_group,
                 size = 2)) +
  scale_shape_manual(values = c(22:25)) +
  scale_fill_manual(values = ugly_colors)
```

